# Generated by Django 6.0.4 on 2026-04-11 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Viendo'), ('completed', 'Completado'), ('dropped', 'Abandonado'), ('plan_to_watch', 'Plan por ver')], default='plan_to_watch', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Usuario',
            },
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_favorite',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='synopsis',
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='useranimelist',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.anime'),
        ),
        migrations.AddField(
            model_name='useranimelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_animes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AlterUniqueTogether(
            name='useranimelist',
            unique_together={('user', 'anime')},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
